name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.7']
        julia-arch: [x64]
        os: [ubuntu-latest, macOS-latest]  # , windows-latest SCIP doesn't work on Windows

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@v1
      - run: julia --project=. -e 'using Pkg; Pkg.test()'